---
driver:
  name: vagrant
  customize:
    cpus: 1
    memory: 2048

provisioner:
  name: chef_zero
  client_rb:
    "Ohai::Config[:disabled_plugins] = [:GCE] #":


platforms:
  - name: ubuntu-14.04
  
suites:
  - name: default
    run_list:
      - recipe[git::default]
      - recipe[apache2::default]
    attributes: { foo: "bar"}
